### ISSUE TITLE
Add connection info to GET /queue

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/PopBox#119]
Include a property containing the  socket connection status at this queue (true while any client connected).

**Comment by aitormagan** [comment]
Is this necessary when someone is peeking a queue?

**Comment by mrutid** [comment]
Let's say "no". Peek operation never involves a Long Connection.

El 16/05/2013, a las 14:12, Aitor Magán García <notifications@github.com<mailto:notifications@github.com>> escribió:

Is this necessary when somebody is peeking a queue?

—
Reply to this email directly or view it on GitHubhttps://github.com/telefonicaid/PopBox/issues/119#issuecomment-17997287.

---

Este mensaje se dirige exclusivamente a su destinatario. Puede consultar nuestra política de envío y recepción de correo electrónico en el enlace situado más abajo.
This message is intended exclusively for its addressee. We only send and receive email on the basis of the terms set out at:
http://www.tid.es/ES/PAGINAS/disclaimer.aspx

**Comment by aitormagan** [comment]
Branch has been merged so this issue can be closed

**Comment by mrutid** [comment]
Add support to multiple clients connected to the same queue. Use a counter instead a boolean to determine connection status.

**Comment by aitormagan** [comment]
It's fixed on commit 97749b6fd811d713f0df886c3a50cc23e0062cbd
