### ISSUE TITLE
[bug] payload is {}

### ISSUE THREAD

**Issue by javiersigler** [telefonicaid/PopBox#15]
Request: {"payload":{},"priority":"H","queue":[{"id":"4QT9J"}]}

Pay attention to the absence of " " in the payload.

Pop: ["[object Object]"]

**Comment by javiersigler** [comment]
It also happens with any json-interpretable text inside of payload as the following:

Request: {"payload":{"message":"err"},"priority":"H","queue":[{"id":"4QT9J"}]}

**Comment by mrutid** [comment]
The Payload MUST be a String. As you can see at examples/Provision.json 

If you wanna send a json message the JSON MUST be stringified (and escaped) in order to fulfill the requirement.

**Comment by mrutid** [comment]
{
"payload" : "MESSAGE",
"priority" : "H",
"callback" :"http://foo.bar",
"qeue" : [
{"id" : "1234JX"},
{"id" : "4QT9JX"}
],
"expirationDate" : "UNIXTIMESTAMP",    //if both present expirationDate will be used
"expirationDelay" : "Seconds"
}

**Comment by javiersigler** [comment]
Okay, mrutid. I know the payload must be an string but I would like to suggest you shall check the payload type and skip the request.

**Comment by mrutid** [comment]
Nice, we will check the content of the payload and provide convenient error message.
