### ISSUE TITLE
Binary friendly behaviour

### ISSUE THREAD

**Issue by fgodino** [telefonicaid/PopBox#84]
Implement a way to accept binary payloads on transactions.

Here is my solution, add a new field in the body providing the encoding format like this

```
{
"payload": "MESSAGE", // the encoded payload
"encoding" ; "utf8" //The enconding here is utf8, could be any string, PopBox doesn check if it is a valid one
"priority":"H",
"callback":"http://foo.bar",
"queue":[
{"id":"Ax"},
{"id":"Bx"}
],
"expirationDate": 1340880820 //UNIXTIMESTAMP 
}
```

Therefore, the response would indicate the encoding of the payload

**Comment by mrutid** [comment]
We will leave this issue as open.

The preferred option will be force end users to encode their Binary Data as a String (for example using B64) into the provision JSON, providing the necessary meta-information to enable an efective decoding by the pop-Client.
