### ISSUE TITLE
Queue - Garbage collector

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/PopBox#92]
Enable a mechanism in order to erase unwanted queues.

Options (under discussion):

*Time since last use/pop/peek/provision:  for example, refreshing expires.
*Statistic Algorimth: erase "fully expired" queues, similar to REDIS expire algorimth. Choose 100 queues, check messages, if all of them are expired erase the queue. If more than X queues have been deleted then repeat.
*Add a remove queue http operation.

**Comment by mrutid** [comment]
is this closed?

f37ffd43ab00311e85aa87355a3c4f5b3e613605

**Comment by aitormagan** [comment]
Yes, it is
